### ISSUE TITLE
Entradas com acentos causam crash

### ISSUE THREAD

**Issue by gallegretti** [adrianob/eliza#11]
->Digite qualquer letra acentuada e o programa vai dar crash

Exemplo:

```
Olá, vamos conversar sobre Breaking Bad?
>é

Traceback (most recent call last):
  File "C:\Users\Gabriel\Documents\GitHub\eliza\eliza.py", line 204, in <module>
    bot.generate_response(input_text.lower())
  File "C:\Users\Gabriel\Documents\GitHub\eliza\eliza.py", line 171, in generate_response
    self.check_for_end(input_text)
  File "C:\Users\Gabriel\Documents\GitHub\eliza\eliza.py", line 121, in check_for_end
    if " ".join(input_text).decode('utf-8') in self.language['quit']:
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 0: unexpected end of data
```

**Comment by adrianob** [comment]
A entrada tem que ser em utf-8. Provavelmente o teu terminal está usando outro encoding.

**Comment by adrianob** [comment]
Ainda assim estamos com problemas pra reconhecer string com acentos. Vou dar uma olhada aqui.

**Comment by adrianob** [comment]
Pronto, mandei um commit arrumando o encoding.
